In [1]:
import pandas as pd
import numpy as np
import sqlite3 as sql
import sys,csv
import matplotlib
from tqdm import tqdm
import pickle
import string
from nltk.corpus import stopwords

from sklearn.metrics import classification_report
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix

In [7]:
db = sql.connect('./2_Database/work_database_v1.db')

In [111]:
df1 = pd.read_sql('SELECT type, content from news where domain != "beforeitsnews.com" and domain != "nytimes.com" and (type = "fake" or type = "reliable")',db)

In [109]:
df = pd.read_sql('SELECT type, content from news', db)

In [15]:
df = pd.read_csv('final_data_for_model.csv')

In [14]:
data_ok.to_csv("final_data_for_model.csv")

NameError: name 'data_ok' is not defined

In [114]:
data_ok = pd.concat([df1,df])

In [16]:
df.head()

Unnamed: 0  type                                            content
0           0     0  Every college basketball fan knows all too wel...
1           1     0  THE WAR HAS BEGUN: The Media Just Attacked Tru...
2           2     0  VIEW GALLERY\n\nThe Boston Celtics are traveli...
3           3     0  Gallup released its annual list of the men and...
4           4     0  One of President Donald Trump’s regular pastim...

In [4]:
df['type'] = df['type'].map({'fake': 0, 'reliable': 1, 'unreliable': 0, 'conspiracy':0})

In [17]:
df.groupby('type').size()

type
0    373737
1    370524
dtype: int64

In [43]:
df = data

In [20]:
df = df.sample(frac = 0.01)

In [45]:
df.count

<bound method DataFrame.count of         Unnamed: 0  type                                            content
0                0     0  Every college basketball fan knows all too wel...
1                1     0  THE WAR HAS BEGUN: The Media Just Attacked Tru...
2                2     0  VIEW GALLERY\n\nThe Boston Celtics are traveli...
3                3     0  Gallup released its annual list of the men and...
4                4     0  One of President Donald Trump’s regular pastim...
...            ...   ...                                                ...
744256      259995     0  Tor\n\nTor is an encrypted anonymising network...
744257      259996     0  Horry County officials want to make sure the m...
744258      259997     0  Raw content\n\nLIMITED OFFICIAL USE PAGE 01 VI...
744259      259998     0  Tor\n\nTor is an encrypted anonymising network...
744260      259999     0  By Shamane Mills\n\nMadison is receiving $$135...

[744261 rows x 3 columns]>

In [22]:
def text_process(mess):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Returns a list of the cleaned text
    """
    # Check characters to see if they are in punctuation
    nopunc = [char for char in mess if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)

    # Now just remove any stopwords
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [8]:
knn_model = pickle.load(open('./3_Sample/finalized_model-knn.sav', 'rb'))
rn_model = pickle.load(open('./3_Sample/finalized_model-rn.sav','rb'))
bayes_model = pickle.load(open('./3_Sample/finalized_model.sav','rb'))

In [46]:
predict_bayes = bayes_model.predict(df['content'])
### Score Naiv Bayes

print(classification_report(predict_bayes,df['type']))
print(confusion_matrix(df['type'], predict_bayes))


### Scor KNN

predict_knn = knn_model.predict(df['content'])

print(classification_report(predict_knn,df['type']))
print(confusion_matrix(df['type'], predict_knn))

### Scor Retele Neuronale
predict_rn = rn_model.predict(df['content'])

print(classification_report(predict_rn,df['type']))
print(confusion_matrix(df['type'], predict_rn))


              precision    recall  f1-score   support

           0       0.83      0.91      0.87    341207
           1       0.92      0.85      0.88    403054

    accuracy                           0.88    744261
   macro avg       0.88      0.88      0.88    744261
weighted avg       0.88      0.88      0.88    744261

[[311596  62141]
 [ 29611 340913]]
              precision    recall  f1-score   support

           0       0.86      0.85      0.85    381333
           1       0.84      0.86      0.85    362928

    accuracy                           0.85    744261
   macro avg       0.85      0.85      0.85    744261
weighted avg       0.85      0.85      0.85    744261

[[322792  50945]
 [ 58541 311983]]


E:\LICENTA\Data set\enviroment\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.50      0.66    744261

    accuracy                           0.50    744261
   macro avg       0.50      0.25      0.33    744261
weighted avg       1.00      0.50      0.66    744261

[[     0 373737]
 [     0 370524]]
